config/routes.rb
Rails.application.routes.draw do
  resources :elements
  # resources :posts
  devise_for :authors
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  scope module: 'authors' do
  	resources :posts do
  	  resources :elements
  	  resources :comments 
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post
  validates :element_type, inclusion: {in: ['paragraph', 'image','video-embed']}
  has_rich_text :content
  has_one_attached :image
  def paragraph?
  	element_type == 'paragraph'
  end

  def image?
  	element_type == 'image'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/comments_controller.rb
module Authors
class CommentsController < AuthorsController

	def  index
    id = (request.original_url.split('/')[-2])
		@posts_for_comment = Post.find(id)
	end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(parent_id: params[:parent_id])
    @prev_comments = @post.comments.where(parent_id: params[:parent_id])
  end

	def create
    @article = Post.find(params[:post_id])
    @comment = @article.comments.create(comment_params)
    redirect_to posts_path
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :parent_id)
    end
end
end

app/controllers/authors/elements_controller.rb
module Authors
class ElementsController < AuthorsController
  before_action :set_post
  before_action :set_element, only: [ :update, :destroy]


  # POST /elements
  def create
    @element = @post.elements.build(element_params)

    if @element.save
      notice = nil
      
    else
      notice = @element.errors.full_messages.join(".")
      
    end
    redirect_to edit_post_path(@post), notice: notice
  end

  # PATCH/PUT /elements/1
  def update
    @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    
  end

  # DELETE /elements/1
  def destroy
    @element.destroy
    redirect_to  edit_post_path(@element.post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = @post.elements.find(params[:id])
    end

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    # Only allow a trusted parameter "white list" through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
end

end

app/controllers/authors/posts_controller.rb
module Authors
class PostsController < AuthorsController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  def index
    @posts = current_author.posts

  end



  # GET /posts/new
  def new
    @post = current_author.posts.build
  end

  # GET /posts/1/edit
  def edit
    @element = @post.elements.build
  end

  # POST /posts
  def create
    @post = current_author.posts.build(post_params)

    if @post.save
      redirect_to edit_post_path(@post)
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to edit_post_path(@post)
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :authenticate_author!
	layout 'authors'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <% @prev_comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <%end%>
    <%= form_with(model: [@post, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', post_path(@post), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/authors/comments/index.html.erb
<div style="background-color:Grey;">
<h2>Comments</h2>
<% @posts_for_comment .comments.each do |comment| %>
<% unless comment.parent_id  %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  

  <%= link_to 'reply', new_post_comment_path(@posts_for_comment, parent_id: comment.id), remote: true, class: 'd-block' %>
  <div id="reply-form-<%= comment.id %>"></div>


<% end %>

<% end%>
<h2>Add a comment:</h2>
<%= form_with model: [ @posts_for_comment, @posts_for_comment.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/authors/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>




  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
	<div class=col-md-3>
		<%= link_to 'Back', posts_path,class: 'btn btn-secondary' %>
		<div class='card'>
			<div class='card-body'>
		       <h4 class="card-title">Editing Post</h4>
		       <%= render 'form', post: @post %>
	        </div>
	    </div>
	</div>
	<div class='col-md-9'>
	 <div class='mb-3' %>
		
		<%= form_with(model: [@post, @element]) do |form| %>
		  <%= form.hidden_field :element_type, value: 'image' %>
		  <%= form.submit  'Image', class: 'btn btn-primary' %>
		<% end %>
	</div>
	<div class='card'>
		<div class='card-body pt-5'>

	<% @post.elements.each do |element| %>
		<% if element.persisted? %>
		 <% if element.image? %>
		  <% if element.image.present? %>
		    <%= image_tag(element.image) %>
		    <%= link_to 'Delete', post_element_path(@post, element),method: :delete,class: 'btn btn-danger mt-2',data: {confirm: 'Are You sure ?'} %>
		    <% else %>

		    
		    <%= form_with(model: [@post, element]) do |form| %>
			  <%= form.file_field :image %>
			  <div class='mt-3'>
			  <%= form.submit  'Save', class: 'btn btn-primary mt-3' %>
			</div>
		    <% end %>
		    <% end %>
		    <% else %>
		    
		    <% end %>
        <% end %>

	<% end %>
</div>
</div>

app/views/authors/posts/index.html.erb
<body>
    <div style="background-color:Blue;">
  <%= link_to 'New Post', new_post_path , class: 'btn btn-primary'%>
  </div>
    <div class="flexDisplay" style="background-color:White;">
        <div class="flexHeight" style="background-color:green;">         
         <button type="button" class="btn btn-success pt-5 MyButton" style="height:100px;width:700px">About Us</button> </br>
         
         <button type="button" class="btn btn-success" style="height:100px;width:700px">Latest News</button></br>
         <button type="button" class="btn btn-success" style="height:100px;width:700px">Today's Weather</button> 
        </div>
        <div class="flexHeightResize2" style="background-color:Gray;">
          
  </div>
 
        <div class="flexHeight" style="background-color:Gray;">         
          <div class='card' style="background-color:Gray;>
    <div class='card-body pt-5'>
 <% @posts.each do |post| %>
   <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
     <div class="card mb-3">
      <div class='card-body'%>
        <h5 class='card-title mb-1 text-dark'style="width:50%"><%= post.title %></h5>
        <p class='text-secondary mb-0'> <%= post.body%></p>
        <% post.elements.each do |element| %>
    <% if element.persisted? %>
     <% if element.image? %>
      <% if element.image.present? %>
        <%= image_tag(element.image) %>
        
       
        <% end %>
       
        <% end %>
        <% end %>

  <% end %>
      </div>
      <%= link_to "View Comment", post_comments_path(post),id: "view-comment", class: 'float-right'%>
     
      <%= link_to "Post Comment", post_comments_path(post) %>
     </div>

   <% end %>
 <% end %>
</div>
</div>

        
        
      </div>
        <div class="flexHeight" style="background-color:Gray;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
</svg>
<p>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg>
</p>
<p>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
</svg>
</p>
        </div>
    </div>

</body>
<script type="text/javascript">
  
  $(document).ready(function() { 
   $('.MyButton').click(function(){
       // CapacityChart();
       alert("uuuu");
    });
  });
</script>

app/views/authors/posts/new.html.erb
<div class="row">
	<div class=col-md-3>
		<h1>New Post</h1>
         <div class='card'>
			<div class='card-body'>
				<%= render 'form', post: @post %>

				<%= link_to 'Back', posts_path %>
			</div>
		</div>
	</div>
	
</div>

app/views/home/index.html.erb
<body>
    <div style="background-color:Blue;">
	<%= link_to 'Start from Here', posts_path , class: 'btn btn-primary'%>
	</div>
    <div class="flexDisplay" style="background-color:White;">
        <div class="flexHeight" style="background-color:Gray;">       	
           <%= image_tag('highcharts.png', class:'rounded') %> 
       <p>Many interesting short-term temperature fluctuations also occur, usually in connection with local weather disturbances. The rapid passage of a mid-latitude cold front, for example, can drop temperatures by 10 °C (18 °F) in a few minutes and, if followed by the sustained movement…</p>
        </div>
        <div class="flexHeightResize" style="background-color:Gray;">
           <%= image_tag('travel.jpg', class:'rounded') %> 
           <p>  While a year of so little leisure travel wasn’t great for our wanderlust, it was nice to see that the planet got a chance to catch its breath. Air and water quality improved, noise pollution was reduced, and in many areas, ecology was restored. As we start looking forward to packing our bags again, we intend to pay homage to this momentum with a renewed commitment to traveling lightly. 

To help inspire a travel reset, we have dedicated this year's Best of Green Awards for Sustainable Travel to finding the people, places, and things that are leading the charge in eco-friendly travel. Seeing the world can be rough on the planet, but doing so through a lens of sustainability can make it much less so. Here’s to a new chapter in travel, one in which we return to globetrotting in all its splendor, watching our footstep along the way</p>
        
        </div>
        <div class="flexHeight" style="background-color:Gray;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
</svg>
<p>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg>
</p>
<p>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
</svg>
</p>
        </div>
    </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class='bg-light'>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>